name: Run e2e tests by label
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
jobs:
  run-e2e-test-by-label:
    if: >
      ${{ contains(['ui-test', 'api-test', 'smoke-test', 'regression-test', 'visual-test'], github.event.pull_request.labels.*.name) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: main
      - run: echo '${{ toJSON(github.event) }}'
      - name: Send event to trigger e2e test
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_E2E_REPO }}
          EVENT_TYPE: github.event.pull_request.labels.*.name
          ORG: longnv1995
          REPO: cicd-flow
        run: |
          curl -d "{\"event_type\": \"${EVENT_TYPE}\"}" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/${ORG}/${REPO}/dispatches"