name: Build Artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Trigger e2e test from other repo
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FOR_E2E_REPO }}
        EVENT_TYPE: run-e2e-test
        ORG: longnv1995
        REPO: cicd-flow
        FROM_REPO: demo-site
      run: |
        curl -X POST https://api.github.com/repos/${ORG}/${REPO}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: token ${GITHUB_TOKEN}' \
          --data '{"event_type": ${EVENT_TYPE}, "client_payload": { "repository": ${FROM_REPO} }}'