name: Build Artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Trigger e2e test from other repo
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FOR_E2E_REPO }}
        EVENT: run-e2e-test
        ORG: longnv1995
        REPO: cicd-flow
      run: |
        curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"