name: Trigger E2E smoke test
on:
  push:
    branches:
      - main
jobs:
  trigger-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Send reposistory dispatch event to e2e-test repo
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.createDispatchEvent({
              owner: 'longnv1995',
              repo: 'cicd-flow',
              event_type: 'run-e2e-test',
              client_payload: {
                branch: 'main',
                repo: 'demo-site',
              },
            });
            console.log(`Repository dispatch event sent: ${response.status}`);
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_E2E_REPO }}